hsfuzz.lo: /home/shou/coding/hsfuzz/corbfuzz/hsfuzz.cc
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/home/shou/coding/hsfuzz/corbfuzz $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /home/shou/coding/hsfuzz/corbfuzz/hsfuzz.cc -o hsfuzz.lo 
$(phplibdir)/hsfuzz.la: ./hsfuzz.la
	$(LIBTOOL) --mode=install cp ./hsfuzz.la $(phplibdir)

./hsfuzz.la: $(shared_objects_hsfuzz) $(HSFUZZ_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_hsfuzz) $(HSFUZZ_SHARED_LIBADD)

